// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/wanglixianyii/go-middleware/go-wire/dao"
	"github.com/wanglixianyii/go-middleware/go-wire/handler"
	"github.com/wanglixianyii/go-middleware/go-wire/router"
	"github.com/wanglixianyii/go-middleware/go-wire/service"
)

// Injectors from wire.go:

func InitializeHandler() *handler.UserHandler {
	engine := router.NewRouterClient()
	userModel := dao.NewUserModel()
	userService := service.NewUserService(userModel)
	userHandler := handler.NewUserHandler(engine, userService)
	return userHandler
}
