// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/wanglixianyii/go-middleware/go-es/common"
	"github.com/wanglixianyii/go-middleware/go-es/config"
	"github.com/wanglixianyii/go-middleware/go-es/dao"
	"github.com/wanglixianyii/go-middleware/go-es/handler"
	"github.com/wanglixianyii/go-middleware/go-es/service"
)

// Injectors from wire.go:

func InitializeHandler(conf *config.ServerConfig) *handler.UserHandler {
	engine := common.NewRouterClient()
	client := common.NewEsClient(conf)
	userES := dao.NewUserES(client)
	userService := service.NewUserService(userES)
	userHandler := handler.NewUserHandler(engine, userService)
	return userHandler
}
